import './style.css';
import {makeScene} from './scene.js';
import {jigTransform} from './math.js';
const $=s=>document.querySelector(s), app=$('#app');
import {template} from './template.js';
app.innerHTML=template;
let data,episodes,arm='arm2',episodeIndex=0,stepIndex=0,draft,scene,playing=null,caseName='normal';
const labels=['베이스 회전 · 현재 —','어깨 들기 · 현재 —','팔꿈치 · 현재 —','손목 굽힘 · 현재 —','손목 회전 · 현재 —','집게 벌림 · 현재 —'];
const status=message=>$('#status').textContent=message;
function persist(){try{localStorage.setItem('so101-demo-v1',JSON.stringify(episodes));status('이 브라우저에 저장했습니다.');}catch{status('브라우저 저장 공간을 사용할 수 없습니다. JSON 내보내기로 보관하세요.');}}
function stop(){clearTimeout(playing);playing=null;$('#play').textContent='경로 미리보기';$('#play-state').textContent='미리보기 정지';}
function page(key){stop();document.querySelectorAll('.page').forEach(p=>p.hidden=p.id!==key);document.querySelectorAll('[data-page]').forEach(b=>{b.classList.toggle('active',b.dataset.page===key);b.setAttribute('aria-current',b.dataset.page===key?'page':'false');});$('#page-title').textContent={teach:'티칭 워크스페이스',camera:'상단 카메라',devices:'장비 모니터링',model:'모델·계산 보정',settings:'설정 · 안내'}[key];if(key==='camera')loadCase(caseName);if(key==='model')drawJig();if(key==='devices')showDevices();}
function episode(){return episodes[episodeIndex];}
function showSteps(){const ep=episode();$('#step-count').textContent=ep.steps.length+'개 스텝';$('#episode-name').value=ep.name;$('#steps').replaceChildren(...ep.steps.map((s,i)=>{const b=document.createElement('button');b.className='step'+(i===stepIndex?' active':'');b.setAttribute('aria-label',`${i+1}. ${s.name}`);b.setAttribute('aria-pressed',String(i===stepIndex));const n=document.createElement('span');n.className='step-num';n.textContent=String(i+1).padStart(2,'0');const title=document.createElement('span');title.textContent=s.name;const tag=document.createElement('small');tag.textContent=s.follow?'지그':'고정';const notice=document.createElement('small');notice.textContent=s.inspection||'—';b.append(n,title,tag,notice);b.draggable=!s.safe;b.ondragstart=()=>dragStep=i;b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();if(dragStep==null||s.safe)return;const moved=ep.steps.splice(dragStep,1)[0];ep.steps.splice(i,0,moved);persist();selectStep(i);dragStep=null;};b.onclick=()=>{stop();selectStep(i);};return b;}));}
function pose(){if(scene){scene.setPose(arm,draft.ticks);scene.setPose(arm==='arm2'?'arm3':'arm2',data.arms[arm==='arm2'?'arm3':'arm2'].safe);}}
function setDirty(){ $('#dirty').textContent='편집 중';$('#dirty').classList.add('changed');pose();}
function selectStep(i){stepIndex=i;draft=structuredClone(episode().steps[i]);showSteps();$('#step-name').value=draft.name;$('#follow').checked=draft.follow;$('#follow').disabled=!!draft.safe;$('#dirty').textContent='저장된 자세';$('#dirty').classList.remove('changed');$('#timeline').max=episode().steps.length-1;$('#timeline').value=i;$('#adjust-step').textContent=draft.name;$('#reference-value').textContent=draft.reference?'X→'+(-draft.reference[1]).toFixed(1)+' · Y↑'+draft.reference[0].toFixed(1)+' mm · '+((draft.reference[2]+90)%360).toFixed(1)+'°':'지그 기준 없음';['ref-x','ref-y','ref-yaw'].forEach((id,k)=>$('#'+id).textContent=draft.reference?[(-draft.reference[1]),draft.reference[0],(draft.reference[2]+90)%360][k].toFixed(1):'—');$('#joints').innerHTML=labels.map((label,i)=>{const [lo,hi]=data.arms[arm].limits[i];return `<div class="joint"><div><label for="joint-${i}">${label}</label><input id="joint-${i}" aria-label="${label} 틱" type="number" min="${lo}" max="${hi}" step="1" value="${draft.ticks[i]}"></div><input id="slider-${i}" aria-label="${label} 조절" type="range" min="${lo}" max="${hi}" value="${draft.ticks[i]}"></div>`;}).join('');labels.forEach((_,i)=>{const number=$('#joint-'+i),range=$('#slider-'+i);const update=e=>{let value=Number(e.target.value);if(!Number.isFinite(value))return;const [lo,hi]=data.arms[arm].limits[i];value=Math.min(hi,Math.max(lo,Math.round(value)));draft.ticks[i]=value;number.value=range.value=value;setDirty();};number.onchange=update;range.oninput=update;});pose();}
function selectArm(id){stop();arm=id;document.querySelectorAll('[data-arm]').forEach(b=>b.classList.toggle('active',b.dataset.arm===id));$('#episode').replaceChildren(...episodes.map((e,i)=>{if(e.arm!==arm)return null;const o=new Option(e.name,i);return o;}).filter(Boolean));episodeIndex=Number($('#episode').value);selectStep(0);}
$('#episode').onchange=()=>{stop();episodeIndex=Number($('#episode').value);selectStep(0);};
$('#step-name').oninput=e=>{draft.name=e.target.value;setDirty();};$('#follow').onchange=e=>{draft.follow=e.target.checked;setDirty();};
$('#save-step').onclick=()=>{if(!draft.name.trim()){status('스텝 이름을 입력하세요.');$('#step-name').focus();return;}episode().steps[stepIndex]=structuredClone(draft);persist();selectStep(stepIndex);};
$('#restore-step').onclick=()=>{selectStep(stepIndex);status('저장된 스텝 자세를 불러왔습니다.');};
$('#add-step').onclick=()=>{stop();const copy=structuredClone(draft);copy.name+=' · 복사';copy.safe=null;episode().steps.splice(stepIndex+1,0,copy);persist();selectStep(stepIndex+1);};
$('#download').onclick=()=>{const blob=new Blob([JSON.stringify({schema:'web-demo-1',source:'browser-demo',hardware_ready:false,episode:episode()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='so101-demo-episode.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('브라우저 체험용 JSON을 내보냈습니다.');};
$('#play').onclick=()=>{if(playing){stop();return;}let i=stepIndex;const tick=()=>{selectStep(i);$('#play').textContent='미리보기 정지';$('#play-state').textContent=`${i+1} / ${episode().steps.length} · ${draft.name}`;$('#steps .active')?.scrollIntoView({block:'nearest'});i++;if(i>=episode().steps.length){playing=setTimeout(()=>{stop();$('#play-state').textContent='미리보기 완료';},Number($('#speed').value));}else playing=setTimeout(tick,Number($('#speed').value));};tick();};
$('#reset-view').onclick=()=>scene?.reset();
$('#reset-demo').onclick=()=>{stop();episodes=structuredClone(data.episodes);try{localStorage.removeItem('so101-demo-v1');}catch{}selectArm('arm2');status('기본 에피소드로 초기화했습니다.');};
for(const b of document.querySelectorAll('[data-page]'))b.onclick=()=>page(b.dataset.page);
for(const b of document.querySelectorAll('[data-go]'))b.onclick=()=>page(b.dataset.go);
for(const b of document.querySelectorAll('[data-arm]'))b.onclick=()=>selectArm(b.dataset.arm);
let caseRequest=0;
async function loadCase(name){if(cameraTab==='detect'){showDetection(name);return;}const request=++caseRequest;caseName=name;$('#case-picker').options[0].text='정상 배치';$('#case-picker').options[1].text='오배치';$('#camera-purpose').textContent='운반 · 리니어 · 완성품 동시 검사';$('#camera-source').textContent='저장된 실물 사진 재생 · 부품·조립 검사';$('.camera-legend').hidden=false;$('#overlay').parentElement.hidden=false;$('#overlay-svg').hidden=!$('#overlay').checked;$('#camera-caption').textContent='점선: 검사 영역 · 실선: CAD 윗면 추정선. 실선은 실제 검출 윤곽과 다를 수 있습니다.';document.querySelectorAll('[data-case]').forEach(b=>b.classList.toggle('active',b.dataset.case===name));const result=await fetch(`./cases/${name}.json`).then(r=>r.json());if(request!==caseRequest)return;const img=$('#case-image');img.src=`./cases/${name}.jpg`;img.onload=()=>{$('#overlay-svg').setAttribute('viewBox',`0 0 ${img.naturalWidth} ${img.naturalHeight}`);};$('#case-status').textContent=name==='normal'?'정상 배치 예시':'부품 누락·오배치 포함';$('#overlay-svg').innerHTML=result.rows.map(r=>{const good=r.quality==='normal';const color=good?'#11bb83':'#ed725c';return [r.roi_display_polygon,r.part_top_polygon].map((p,i)=>p?.length?`<polygon points="${p.map(x=>x.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="2.2" ${i===0?'stroke-dasharray="9 5"':''}/>`:'').join('');}).join('');$('#case-rows').replaceChildren(...result.rows.map(r=>{const row=document.createElement('button');row.className='result-row '+(r.quality==='normal'?'normal':'abnormal');const a=document.createElement('span');a.textContent=({a_cap:'운반 A 상단',a_insert:'A 중단',a_housing:'운반 A 하단',b_cap:'운반 B 상단',b_insert:'B 중단',b_tpu:'운반 B 중단',a_ball:'운반 A 중단','linear_1.5_0':'리니어 좌측 A용','linear_1.5_1':'리니어 우측 B용',b_housing:'운반 B 하단',linear_a:'리니어 A',linear_b:'리니어 B',finished:'완성품'})[r.id]||r.id;const b=document.createElement('b');b.textContent=r.label;const c=document.createElement('small');c.textContent=Number.isFinite(r.score)?r.score+'점':'—';row.append(a,b,c);row.onclick=()=>{$('#case-detail').textContent=r.id==='a_cap'&&name==='faults'?'A 상단의 방향 차이는 16.1°로 허용값 12°를 넘습니다. 검사 영역 경계에도 걸쳐 부정확한 안착으로 판정했습니다.':r.id==='b_housing'&&name==='faults'?'B 하단이 있어야 하는 칸에 A 하단이 있습니다. 일치도 78점만으로 정상 처리하지 않고 부품 종류를 함께 확인합니다.':r.id==='finished'?'상단 결합 형상으로 완성 상태를 구분합니다. 가려진 내부 부품은 이 영상만으로 확인할 수 없습니다.':`${a.textContent}: ${r.label}. 현재 사진에 검사 코드를 적용한 저장 결과입니다.`;};return row;}));$('#case-detail').textContent=name==='normal'?'각 행을 선택하면 판정 설명을 볼 수 있습니다. 비어 있는 리니어는 기대 상태에 따라 통과 여부가 달라집니다.':'A 상단 기울어짐, A 하단 누락, B 하단 칸의 다른 부품, 미완성 제품을 비교해 보세요.';}
for(const b of document.querySelectorAll('[data-case]'))b.onclick=()=>loadCase(b.dataset.case);
$('#overlay').onchange=e=>$('#overlay-svg').hidden=!e.target.checked;
function drawJig(){const dx=Number($('#x').value),dy=Number($('#y').value),angle=Number($('#angle').value);[['x',dx,'mm'],['y',dy,'mm'],['angle',angle,'°']].forEach(([k,v,u])=>$('#'+k+'-out').textContent=v+u);const old=[200,100,0],current=[200+dx,100+dy,angle],point=[220,100,30],symmetry=Number($('#symmetry').value);const p=jigTransform(point,old,current,symmetry);$('#corrected-tcp').textContent=`(${p[0].toFixed(2)}, ${p[1].toFixed(2)})`;const map=p=>[350+(p[0]-200)*3,210-(p[1]-100)*3];const poly=pose=>[[-22,-15],[22,-15],[22,15],[-22,15]].map(([x,y])=>map(jigTransform([200+x,100+y,0],old,pose,symmetry)).join(',')).join(' ');const a=map(point),b=map(p),c=map(current);$('#jig-svg').innerHTML=`<defs><pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse"><path d="M30 0H0V30" fill="none" stroke="#dbe3e9"/></pattern></defs><rect width="700" height="420" fill="url(#grid)"/><polygon points="${poly(old)}" fill="#94a9b41a" stroke="#91a4b0" stroke-width="2" stroke-dasharray="7 5"/><polygon points="${poly(current)}" fill="#11697a18" stroke="#11697a" stroke-width="3"/><path d="M${a} L${b}" stroke="#d88b35" stroke-width="2" stroke-dasharray="5 4"/><circle cx="${a[0]}" cy="${a[1]}" r="6" fill="#8196a2"/><circle cx="${b[0]}" cy="${b[1]}" r="8" fill="#d88b35"/><circle cx="${c[0]}" cy="${c[1]}" r="4" fill="#11697a"/><text x="25" y="35" fill="#526477" font-size="15">회색: 티칭 기준</text><text x="25" y="62" fill="#11697a" font-size="15">청록: 현재 지그 / 주황: 보정 TCP</text>`;$('#jig-svg text').textContent='회색: 티칭 기준';}
for(const id of ['x','y','angle','symmetry'])$('#'+id).oninput=drawJig;
let dragStep=null,cameraTab='detect';
function teachTab(tab){stop();document.querySelectorAll('[data-teach-tab]').forEach(b=>b.classList.toggle('active',b.dataset.teachTab===tab));$('.editor').hidden=tab==='adjust';$('.adjust-panel').hidden=tab!=='adjust';$('.teaching-grid').classList.toggle('adjusting',tab==='adjust');}
for(const b of document.querySelectorAll('[data-teach-tab]'))b.onclick=()=>teachTab(b.dataset.teachTab);
$('#open-adjust').onclick=()=>teachTab('adjust');$('#stop-all').onclick=()=>{stop();status('웹 미리보기를 멈췄습니다.');};$('#pause').onclick=stop;$('#rewind').onclick=()=>{stop();selectStep(0);};$('#timeline').oninput=e=>{stop();selectStep(Number(e.target.value));};$('#workcell-view').onclick=()=>scene?.reset();
$('#save-episode').onclick=()=>{if(!$('#episode-name').value.trim()){status('에피소드 이름을 입력하세요.');return;}episode().name=$('#episode-name').value.trim();persist();const selected=episodeIndex;selectArm(arm);$('#episode').value=selected;episodeIndex=selected;selectStep(0);};
$('#new-episode').onclick=()=>{const e={name:'새 에피소드',arm,steps:[structuredClone(episode().steps[0])]};episodes.push(e);selectArm(arm);episodeIndex=episodes.length-1;$('#episode').value=episodeIndex;selectStep(0);persist();};
$('#copy-episode').onclick=()=>{const e=structuredClone(episode());e.name+=' · 복사';episodes.push(e);selectArm(arm);episodeIndex=episodes.length-1;$('#episode').value=episodeIndex;selectStep(0);persist();};
$('#delete-episode').onclick=()=>{if(episodes.filter(e=>e.arm===arm).length<2){status('팔별로 에피소드 하나는 남겨 두세요.');return;}episodes.splice(episodeIndex,1);selectArm(arm);persist();};
$('#delete-step').onclick=()=>{if(episode().steps[stepIndex].safe){status('시작·종료 안전 자세는 삭제할 수 없습니다.');return;}episode().steps.splice(stepIndex,1);selectStep(Math.max(0,stepIndex-1));persist();};
$('#safe-step').onclick=()=>{const i=episode().steps.findIndex(s=>s.safe==='start');selectStep(i<0?0:i);status('시작 안전 자세를 불러왔습니다. 관절 값을 편집한 뒤 선택 스텝 수정으로 저장하세요.');};
$('#comparison-toggle').onclick=()=>{const body=$('#comparison-body');body.hidden=!body.hidden;$('#comparison-toggle').textContent=body.hidden?'▶ 펼치기':'▼ 접기';};
$('#jig-principle').onclick=drawJig;$('#reread-jig').onclick=()=>{page('camera');status('저장된 검출 사례를 표시합니다. 웹에서는 새 카메라 측정을 수행하지 않습니다.');};
$('#video-link').onclick=()=>window.open('https://drive.google.com/file/d/1SaLd2PngmwPD5W_nLa0g0v4liUucD5go/view','_blank','noopener');
$('#case-picker').onchange=e=>loadCase(e.target.value);
for(const b of document.querySelectorAll('[data-camera-tab]'))b.onclick=()=>{cameraTab=b.dataset.cameraTab;document.querySelectorAll('[data-camera-tab]').forEach(x=>x.classList.toggle('active',x===b));loadCase(caseName);};
$('#camera-display').onchange=e=>{$('.camera-grid').hidden=e.target.selectedIndex===1;$('.cad').hidden=e.target.selectedIndex!==1;};
$('#save-image').onclick=()=>{const a=document.createElement('a');a.href=$('#case-image').src;a.download=cameraTab==='detect'?'jig-detection.png':'inspection-source.jpg';a.click();};
function showDevices(){$('#device-panels').innerHTML=['arm2','arm3'].map(id=>{const ticks=id===arm?draft.ticks:data.arms[id].safe;return `<section><h2>로봇팔 ${id.slice(-1)} · 미연결</h2><p class="source-caption">웹 데모 · 편집 목표만 표시</p><table><thead><tr><th>관절</th><th>목표 틱</th><th>실물 틱</th><th>부하</th><th>전류</th><th>상태</th></tr></thead><tbody>${labels.map((name,i)=>`<tr><td>${name.split(' ·')[0]}</td><td>${ticks[i]}</td><td>—</td><td>—</td><td>—</td><td>미연결</td></tr>`).join('')}</tbody></table></section>`;}).join('');}

function showDetection(name){caseRequest++;caseName=name;$('#case-picker').options[0].text='지그 있음';$('#case-picker').options[1].text='운반 지그 없음';const present=name==='normal';$('#case-image').src=present?'./cases/jig-detected.png':'./cases/jig-absent.png';$('#overlay-svg').hidden=true;$('#case-status').textContent='지그 검출 · 저장 사례';$('#camera-source').textContent=present?'저장된 실물 사진 · 운반용 지그 검출':'실물 카메라 촬영 · 운반용 지그 없음';$('#camera-purpose').textContent='지그 위치·방향 확인';$('.camera-legend').hidden=true;$('#overlay').parentElement.hidden=true;$('#camera-caption').textContent='카메라 검출 위치·방향을 채택한 뒤 티칭 기준과 비교합니다. 지그를 못 찾으면 새 위치를 만들지 않습니다.';$('#case-rows').innerHTML=present?'<div class="result-row"><span>운반용 지그</span><b>검출됨 · 위치·방향 확인</b><small>—</small></div><div class="result-row"><span>완제품 팔레트</span><b>제품에 가려짐</b><small>—</small></div>':'<div class="result-row"><span>운반용 지그</span><b>없음 · not_found</b><small>—</small></div><div class="result-row"><span>완제품 팔레트</span><b>빈 팔레트 검출</b><small>—</small></div>';$('#case-detail').textContent='지그가 이동·회전한 뒤의 실물 티칭 적용은 아래 검증 영상에서 확인할 수 있습니다.';}
try {data=await fetch('./demo-data.json').then(r=>r.json());episodes=structuredClone(data.episodes);try{const saved=JSON.parse(localStorage.getItem('so101-demo-v1'));if(Array.isArray(saved)&&saved.length>0&&saved.every(e=>data.arms[e.arm]&&Array.isArray(e.steps)&&e.steps.length&&e.steps.every(s=>typeof s.name==='string'&&Array.isArray(s.ticks)&&s.ticks.length===6&&s.ticks.every(Number.isFinite))))episodes=saved;}catch{}selectArm('arm2');page('teach');scene=await makeScene($('#scene'),data);$('#scene .loading')?.remove();pose();status('준비 완료 · 스텝 선택, 관절 편집, 카메라 검사 사례를 체험하세요.');} catch(error){console.error(error);status('데모를 불러오지 못했습니다. 새로고침 후 다시 시도하세요.');$('#scene .loading').textContent=error.message;}
